### PR TITLE
Fix the box arrow

### LINKED ISSUE #4: The Arrow is not aligned with the box
Here is a screenshot of the problem:
Képernyőfotó 2023-02-23 - 11 08 16

### PR DESCRIPTION
**Pull request by Gyurmatag**

### CODE REVIEW

File: frontend/source/components/holed-layer/holed-layer.vue [hunk 1]
```diff
@@ -44,6 +44,8 @@ const boxTop = computed(() => {
 	return `${calculatedTop}px`;
 });
 const boxLeft = computed(() => calculateTutorialBoxLeft(currentStep.value.width, currentStep.value.selector, currentElementBoundingRect.value));
+const boxLeftWithPx = computed(() => `${boxLeft.value}px`);
```
Comment (Gyapi24) [inline frontend/source/components/holed-layer/holed-layer.vue]: why use separate computed, you could just us it like:
``const boxLeft = computed(() => {
const boxLeftValue = calculateTutorialBoxLeft(currentStep.value.width, currentStep.value.selector, currentElementBoundingRect.value);
return `${boxLeftValue}px`
});``

Comment (Gyurmatag) [reply frontend/source/components/holed-layer/holed-layer.vue]: I can't because I use the pure boxLeft.value just in line 48.
`const arrowLeft = computed(() => `${currentElementBoundingRect.value.left - boxLeft.value}px`);`

Comment (Gyurmatag) [reply frontend/source/components/holed-layer/holed-layer.vue]: Anyways... It doesn't matter now because I added a global removePxSuffix function that does the job here.

**Review by sarkiroka — APPROVED** [review]
lgtm
